# Generated by Django 4.0.3 on 2022-04-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_details',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
